package io.queryaudit.core.detector;

import io.queryaudit.core.model.IndexInfo;
import io.queryaudit.core.model.IndexMetadata;
import io.queryaudit.core.model.Issue;
import io.queryaudit.core.model.IssueType;
import io.queryaudit.core.model.QueryRecord;
import io.queryaudit.core.model.Severity;
import io.queryaudit.core.parser.EnhancedSqlParser;
import io.queryaudit.core.parser.SqlParser;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Detects tables with too many indexes, which causes write amplification. Every INSERT/UPDATE must
 * maintain all indexes on the table, so excessive indexes degrade write performance.
 *
 * <p>Threshold: more than 6 indexes triggers a WARNING.
 *
 * @author haroya
 * @since 0.2.0
 */
public class WriteAmplificationDetector implements DetectionRule {

  private static final int DEFAULT_INDEX_THRESHOLD = 6;

  private final int indexThreshold;

  public WriteAmplificationDetector() {
    this(DEFAULT_INDEX_THRESHOLD);
  }

  public WriteAmplificationDetector(int indexThreshold) {
    this.indexThreshold = indexThreshold;
  }

  @Override
  public List<Issue> evaluate(List<QueryRecord> queries, IndexMetadata indexMetadata) {
    List<Issue> issues = new ArrayList<>();

    if (indexMetadata == null || indexMetadata.isEmpty()) {
      return issues;
    }

    // Collect all table names referenced in queries
    Set<String> tables = new LinkedHashSet<>();
    for (QueryRecord query : queries) {
      String sql = query.sql();
      if (sql != null) {
        tables.addAll(EnhancedSqlParser.extractTableNames(sql));
      }
    }

    Set<String> seen = new HashSet<>();

    for (String table : tables) {
      if (!seen.add(table)) {
        continue;
      }

      List<IndexInfo> allIndexes = indexMetadata.getIndexesForTable(table);
      if (allIndexes.isEmpty()) {
        continue;
      }

      // Count distinct index names, excluding auto-generated ones.
      // H2 auto-generates FK indexes (FK_xxx, CONSTRAINT_xxx, SYS_xxx) that
      // don't exist in production (MySQL/PostgreSQL), inflating the count.
      long indexCount =
          allIndexes.stream()
              .map(IndexInfo::indexName)
              .filter(name -> name != null)
              .filter(name -> !isAutoGeneratedIndex(name))
              .distinct()
              .count();

      if (indexCount > indexThreshold) {
        issues.add(
            new Issue(
                IssueType.WRITE_AMPLIFICATION,
                Severity.WARNING,
                null,
                table,
                null,
                "Table '"
                    + table
                    + "' has "
                    + indexCount
                    + " indexes. Each INSERT/UPDATE maintains all indexes.",
                "Review if all "
                    + indexCount
                    + " indexes are necessary. Consider dropping unused indexes. "
                    + "Each extra index adds write overhead."));
      }
    }

    return issues;
  }

  /**
   * Returns true if the index name looks auto-generated by the database engine rather than
   * user-defined. H2 auto-generates FK constraint indexes with names like {@code FK_xxx}, {@code
   * CONSTRAINT_xxx}, or {@code SYS_xxx} that don't exist in production databases
   * (MySQL/PostgreSQL).
   */
  private static boolean isAutoGeneratedIndex(String indexName) {
    String upper = indexName.toUpperCase();
    return upper.startsWith("FK_")
        || upper.startsWith("CONSTRAINT_")
        || upper.startsWith("SYS_")
        || upper.startsWith("FKIDX_");
  }
}
