#!/usr/bin/env python3
"""Compare a bounded, versioned public API directly from JVM class files.

No third-party package, network access, source parser, or javap-output parsing is needed.
The baseline is an explicit compatibility floor, never regenerated by a normal check.
This checks declared public/protected signatures, not behavior, inherited-member equivalence,
annotation values, constant values, serialization layout, or complete Java overload resolution.
"""

import argparse
import json
import struct
import sys
from pathlib import Path


SCHEMA_VERSION = 1
PUBLIC, PRIVATE, PROTECTED, STATIC, FINAL = 1, 2, 4, 8, 16
ABSTRACT, INTERFACE, ANNOTATION, ENUM = 1024, 512, 8192, 16384
CLASS_FLAGS = PUBLIC | PRIVATE | PROTECTED | STATIC | FINAL | ABSTRACT | INTERFACE | ANNOTATION | ENUM
MEMBER_FLAGS = PUBLIC | PROTECTED | STATIC | FINAL | ABSTRACT | 128  # varargs for methods
PREFIXES = (
    "io/queryaudit/core/contract/",
    "io/queryaudit/core/extension/",
    "io/queryaudit/core/model/",
    "io/queryaudit/core/reporter/",
)
ENTRY_POINTS = (
    # JUnit 5 annotations and extension behaviour.
    "io/queryaudit/junit5/BooleanOverride",
    "io/queryaudit/junit5/DetectNPlusOne",
    "io/queryaudit/junit5/EnableQueryInspector",
    "io/queryaudit/junit5/ExpectMaxQueryCount",
    "io/queryaudit/junit5/ExpectQueries",
    "io/queryaudit/junit5/QueryAudit",
    "io/queryaudit/junit5/QueryAuditDataSourceStore",
    "io/queryaudit/junit5/QueryAuditExclude",
    "io/queryaudit/junit5/QueryAuditExtension",
    # Spring Boot configuration properties.
    "io/queryaudit/spring/QueryAuditProperties",
    # Programmatic configuration.
    "io/queryaudit/core/config/AuditMode",
    "io/queryaudit/core/config/QueryAuditConfig",
    "io/queryaudit/core/config/ReportFormat",
    "io/queryaudit/core/config/ReportRedaction",
    "io/queryaudit/core/config/RuleProfile",
    # Custom rule and metadata provider SPIs.
    "io/queryaudit/core/detector/DetectionRule",
    "io/queryaudit/core/detector/QueryAuditAnalyzer",
    "io/queryaudit/core/analyzer/ExplainAnalysisException",
    "io/queryaudit/core/analyzer/ExplainAnalyzer",
    "io/queryaudit/core/analyzer/IndexMetadataProvider",
    # Capture scoping for background work.
    "io/queryaudit/core/interceptor/QueryCaptureSession",
    # Recorded query count contracts.
    "io/queryaudit/core/regression/QueryContracts",
    "io/queryaudit/core/regression/QueryCountBaseline",
    "io/queryaudit/core/regression/QueryCounts",
)
EXCLUDED_PREFIXES = ("io/queryaudit/core/extension/internal/",)


class Reader:
    def __init__(self, data):
        self.data = data
        self.offset = 0

    def take(self, count):
        if self.offset + count > len(self.data):
            raise ValueError("Truncated class file")
        result = self.data[self.offset : self.offset + count]
        self.offset += count
        return result

    def u1(self):
        return self.take(1)[0]

    def u2(self):
        return struct.unpack(">H", self.take(2))[0]

    def u4(self):
        return struct.unpack(">I", self.take(4))[0]


def read_class(path):
    reader = Reader(Path(path).read_bytes())
    if reader.u4() != 0xCAFEBABE:
        raise ValueError(f"Not a JVM class file: {path}")
    reader.u2()  # minor version: Java 17 and 21 output should describe the same API
    reader.u2()  # major version
    pool = [None] * reader.u2()
    index = 1
    while index < len(pool):
        tag = reader.u1()
        if tag == 1:
            # Public names/signatures in this project's compatibility scope are ASCII.
            # Latin-1 preserves every byte, including modified-UTF8, for exact comparisons.
            pool[index] = reader.take(reader.u2()).decode("latin-1")
        elif tag in (7, 8, 16, 19, 20):
            pool[index] = (tag, reader.u2())
        elif tag in (3, 4, 9, 10, 11, 12, 17, 18):
            reader.take(4)
        elif tag in (5, 6):
            reader.take(8)
            index += 1
        elif tag == 15:
            reader.take(3)
        else:
            raise ValueError(f"Unsupported constant-pool tag {tag}: {path}")
        index += 1

    def class_name(reference):
        return None if reference == 0 else pool[pool[reference][1]]

    def attributes():
        values = {}
        for _ in range(reader.u2()):
            name = pool[reader.u2()]
            values[name] = reader.take(reader.u4())
        return values

    def signature(values):
        value = values.get("Signature")
        return None if value is None else pool[Reader(value).u2()]

    def members(is_method):
        values = {}
        for _ in range(reader.u2()):
            flags, name, descriptor = reader.u2(), pool[reader.u2()], pool[reader.u2()]
            attrs = attributes()
            if not flags & (PUBLIC | PROTECTED):
                continue
            exceptions = Reader(attrs.get("Exceptions", b"\x00\x00"))
            values[name + descriptor] = {
                "flags": flags & (MEMBER_FLAGS if is_method else MEMBER_FLAGS & ~128),
                "signature": signature(attrs),
                "exceptions": sorted(class_name(exceptions.u2()) for _ in range(exceptions.u2())),
                "annotation_default": "AnnotationDefault" in attrs,
            }
        return values

    flags, this_class = reader.u2(), reader.u2()
    name = class_name(this_class)
    superclass = class_name(reader.u2())
    interfaces = sorted(class_name(reader.u2()) for _ in range(reader.u2()))
    fields, methods = members(False), members(True)
    attrs = attributes()
    if "InnerClasses" in attrs:
        inner = Reader(attrs["InnerClasses"])
        for _ in range(inner.u2()):
            reference, _, _, inner_flags = inner.u2(), inner.u2(), inner.u2(), inner.u2()
            if reference == this_class:
                flags = (flags & ~CLASS_FLAGS) | (inner_flags & CLASS_FLAGS)
    permitted = Reader(attrs.get("PermittedSubclasses", b"\x00\x00"))
    return name, {
        "flags": flags & CLASS_FLAGS,
        "superclass": superclass,
        "interfaces": interfaces,
        "signature": signature(attrs),
        "permitted_subclasses": sorted(class_name(permitted.u2()) for _ in range(permitted.u2())),
        "fields": fields,
        "methods": methods,
    }


def in_scope(name):
    if name.startswith(EXCLUDED_PREFIXES):
        return False
    return name.startswith(PREFIXES) or any(name == value or name.startswith(value + "$") for value in ENTRY_POINTS)


def snapshot(directories, restrict_scope=True):
    found = {}
    for directory in directories:
        directory = Path(directory)
        if not directory.is_dir():
            raise ValueError(f"Compiled classes directory is missing: {directory}")
        for path in sorted(directory.rglob("*.class")):
            name, api = read_class(path)
            if name in found:
                raise ValueError(f"Duplicate class on API input paths: {name}")
            found[name] = api
    classes = {}
    for name, api in found.items():
        if restrict_scope and not in_scope(name):
            continue
        components = name.split("$")
        owners = ["$".join(components[:index]) for index in range(1, len(components))]
        if api["flags"] & (PUBLIC | PROTECTED) and all(
            found[owner]["flags"] & (PUBLIC | PROTECTED) for owner in owners if owner in found
        ):
            classes[name] = api
    if not classes:
        raise ValueError("No public API classes found; refusing an empty compatibility snapshot")
    return dict(sorted(classes.items()))


def differences(baseline, current):
    failures = []
    for name, previous in baseline.items():
        label = name.replace("/", ".")
        candidate = current.get(name)
        if candidate is None:
            failures.append(f"{label}: public type removed or no longer visible")
            continue
        for key in ("flags", "superclass", "signature", "permitted_subclasses"):
            if previous[key] != candidate[key]:
                failures.append(f"{label}: class {key} changed")
        if not set(previous["interfaces"]).issubset(candidate["interfaces"]):
            failures.append(f"{label}: an implemented interface was removed")
        for category in ("fields", "methods"):
            for member, old in previous[category].items():
                new = candidate[category].get(member)
                member_label = f"{label}.{member}"
                if new is None:
                    failures.append(f"{member_label}: {category[:-1]} removed or JVM descriptor changed")
                    continue
                for key in ("flags", "signature", "exceptions"):
                    if old[key] != new[key]:
                        failures.append(f"{member_label}: {key} changed")
                if old["annotation_default"] and not new["annotation_default"]:
                    failures.append(f"{member_label}: annotation default removed")
        for member, added in candidate["methods"].items():
            if member not in previous["methods"] and added["flags"] & ABSTRACT and not added["annotation_default"]:
                failures.append(f"{label}.{member}: new abstract method breaks existing implementers")
    return failures


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "snapshot"))
    parser.add_argument("--classes", nargs="+", required=True, type=Path)
    parser.add_argument("--baseline", type=Path)
    parser.add_argument("--source-revision")
    args = parser.parse_args(argv)
    try:
        current = snapshot(args.classes)
        if args.command == "snapshot":
            if not args.source_revision:
                parser.error("snapshot requires the exact --source-revision used to compile these classes")
            print(json.dumps({"schema_version": SCHEMA_VERSION, "source_revision": args.source_revision,
                "scope": {"prefixes": PREFIXES, "entry_points": ENTRY_POINTS,
                    "excluded": list(EXCLUDED_PREFIXES)}, "classes": current}, indent=2, sort_keys=True))
            return 0
        if args.baseline is None:
            parser.error("check requires --baseline")
        baseline = json.loads(args.baseline.read_text(encoding="utf-8"))
        if baseline.get("schema_version") != SCHEMA_VERSION or not baseline.get("classes"):
            raise ValueError("Unsupported or empty API baseline")
        failures = differences(baseline["classes"], current)
        if failures:
            print("Public API compatibility check failed:", file=sys.stderr)
            for failure in failures:
                print(f"  - {failure}", file=sys.stderr)
            return 1
        print(f"Public API compatibility passed: {len(baseline['classes'])} baseline types; additions permitted")
        return 0
    except (OSError, ValueError, KeyError, struct.error) as failure:
        print(f"Cannot verify public API: {failure}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
