package io.queryaudit.core.detector;

import static org.assertj.core.api.Assertions.assertThat;

import io.queryaudit.core.config.QueryAuditConfig;
import io.queryaudit.core.model.IndexInfo;
import io.queryaudit.core.model.IndexMetadata;
import io.queryaudit.core.model.Issue;
import io.queryaudit.core.model.IssueType;
import io.queryaudit.core.model.QueryAuditReport;
import io.queryaudit.core.model.QueryRecord;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Real-world SQL corpus benchmark test.
 *
 * <p>Runs ALL detectors via {@link QueryAuditAnalyzer} against realistic SQL queries generated by
 * Hibernate/JPA, MyBatis, plain JDBC, and reporting tools. Tracks and reports precision metrics
 * (true positives vs. false positives).
 *
 * <p>Each corpus section documents which queries SHOULD trigger detections (true positives) and
 * which should NOT (potential false positives).
 */
class RealWorldCorpusBenchmarkTest {

  private static QueryAuditAnalyzer analyzer;

  @BeforeAll
  static void setUp() {
    // Use an empty baseline so nothing is pre-acknowledged
    analyzer = new QueryAuditAnalyzer(QueryAuditConfig.defaults(), List.of());
  }

  // ---------------------------------------------------------------
  // Helper: create a QueryRecord from raw SQL
  // ---------------------------------------------------------------
  private static QueryRecord record(String sql) {
    return new QueryRecord(sql, 1_000L, System.currentTimeMillis(), "");
  }

  private static QueryRecord slowRecord(String sql) {
    // 5 seconds in nanos -- triggers slow-query detector
    return new QueryRecord(sql, 5_000_000_000L, System.currentTimeMillis(), "");
  }

  // ---------------------------------------------------------------
  // Schema definitions
  // ---------------------------------------------------------------

  /**
   * PetClinic schema: - owners(id PK, first_name, last_name idx, address, city, telephone) -
   * types(id PK, name idx) - pets(id PK, name, birth_date, type_id idx, owner_id idx) - visits(id
   * PK, visit_date, description, pet_id idx) - vets(id PK, first_name, last_name idx) -
   * specialties(id PK, name idx) - vet_specialties(vet_id idx, specialty_id idx)
   */
  private static IndexMetadata createPetClinicSchema() {
    Map<String, List<IndexInfo>> indexes = new HashMap<>();

    indexes.put(
        "owners",
        List.of(
            new IndexInfo("owners", "PRIMARY", "id", 1, false, 1000),
            new IndexInfo("owners", "idx_last_name", "last_name", 1, true, 800)));
    indexes.put(
        "types",
        List.of(
            new IndexInfo("types", "PRIMARY", "id", 1, false, 20),
            new IndexInfo("types", "idx_name", "name", 1, true, 20)));
    indexes.put(
        "pets",
        List.of(
            new IndexInfo("pets", "PRIMARY", "id", 1, false, 500),
            new IndexInfo("pets", "idx_owner_id", "owner_id", 1, true, 200),
            new IndexInfo("pets", "idx_type_id", "type_id", 1, true, 20)));
    indexes.put(
        "visits",
        List.of(
            new IndexInfo("visits", "PRIMARY", "id", 1, false, 2000),
            new IndexInfo("visits", "idx_pet_id", "pet_id", 1, true, 500)));
    indexes.put(
        "vets",
        List.of(
            new IndexInfo("vets", "PRIMARY", "id", 1, false, 50),
            new IndexInfo("vets", "idx_last_name", "last_name", 1, true, 50)));
    indexes.put(
        "specialties",
        List.of(
            new IndexInfo("specialties", "PRIMARY", "id", 1, false, 10),
            new IndexInfo("specialties", "idx_name", "name", 1, true, 10)));
    indexes.put(
        "vet_specialties",
        List.of(
            new IndexInfo("vet_specialties", "idx_vet_id", "vet_id", 1, true, 50),
            new IndexInfo("vet_specialties", "idx_specialty_id", "specialty_id", 1, true, 10)));

    return new IndexMetadata(indexes);
  }

  /**
   * E-commerce schema: - users(id PK, email idx_unique, username idx, password_hash, created_at,
   * status) - products(id PK, name, sku idx_unique, category_id idx, price, stock_quantity,
   * created_at) - categories(id PK, name idx, parent_id idx) - orders(id PK, user_id idx, status,
   * total_amount, created_at idx, shipping_address) - order_items(id PK, order_id idx, product_id
   * idx, quantity, unit_price) - cart_items(id PK, user_id idx, product_id idx, quantity,
   * created_at) - payments(id PK, order_id idx_unique, payment_method, amount, status,
   * transaction_id idx, created_at) - reviews(id PK, product_id idx, user_id idx, rating, comment,
   * created_at) - inventory_log(id PK, product_id idx, change_amount, reason, created_at)
   */
  private static IndexMetadata createEcommerceSchema() {
    Map<String, List<IndexInfo>> indexes = new HashMap<>();

    indexes.put(
        "users",
        List.of(
            new IndexInfo("users", "PRIMARY", "id", 1, false, 50000),
            new IndexInfo("users", "idx_email", "email", 1, false, 50000),
            new IndexInfo("users", "idx_username", "username", 1, true, 50000)));
    indexes.put(
        "products",
        List.of(
            new IndexInfo("products", "PRIMARY", "id", 1, false, 10000),
            new IndexInfo("products", "idx_sku", "sku", 1, false, 10000),
            new IndexInfo("products", "idx_category_id", "category_id", 1, true, 500)));
    indexes.put(
        "categories",
        List.of(
            new IndexInfo("categories", "PRIMARY", "id", 1, false, 200),
            new IndexInfo("categories", "idx_name", "name", 1, true, 200),
            new IndexInfo("categories", "idx_parent_id", "parent_id", 1, true, 50)));
    indexes.put(
        "orders",
        List.of(
            new IndexInfo("orders", "PRIMARY", "id", 1, false, 100000),
            new IndexInfo("orders", "idx_user_id", "user_id", 1, true, 50000),
            new IndexInfo("orders", "idx_created_at", "created_at", 1, true, 80000)));
    indexes.put(
        "order_items",
        List.of(
            new IndexInfo("order_items", "PRIMARY", "id", 1, false, 300000),
            new IndexInfo("order_items", "idx_order_id", "order_id", 1, true, 100000),
            new IndexInfo("order_items", "idx_product_id", "product_id", 1, true, 10000)));
    indexes.put(
        "cart_items",
        List.of(
            new IndexInfo("cart_items", "PRIMARY", "id", 1, false, 20000),
            new IndexInfo("cart_items", "idx_user_id", "user_id", 1, true, 15000),
            new IndexInfo("cart_items", "idx_product_id", "product_id", 1, true, 10000)));
    indexes.put(
        "payments",
        List.of(
            new IndexInfo("payments", "PRIMARY", "id", 1, false, 100000),
            new IndexInfo("payments", "idx_order_id", "order_id", 1, false, 100000),
            new IndexInfo("payments", "idx_transaction_id", "transaction_id", 1, true, 100000)));
    indexes.put(
        "reviews",
        List.of(
            new IndexInfo("reviews", "PRIMARY", "id", 1, false, 50000),
            new IndexInfo("reviews", "idx_product_id", "product_id", 1, true, 10000),
            new IndexInfo("reviews", "idx_user_id", "user_id", 1, true, 50000)));
    indexes.put(
        "inventory_log",
        List.of(
            new IndexInfo("inventory_log", "PRIMARY", "id", 1, false, 200000),
            new IndexInfo("inventory_log", "idx_product_id", "product_id", 1, true, 10000)));

    return new IndexMetadata(indexes);
  }

  /**
   * Hibernate/JPA demo schema: - users(id PK, name, email idx, version, created_at) - teams(id PK,
   * name idx, description) - members(id PK, name, team_id idx, role, joined_at) - posts(id PK,
   * title, body, author_id idx, category, published, created_at idx, version) - comments(id PK,
   * post_id idx, author_id idx, content, created_at) - tags(id PK, name idx_unique) -
   * post_tags(post_id idx, tag_id idx) - audit_log(id PK, entity_type, entity_id, action,
   * created_at idx, user_id idx)
   */
  private static IndexMetadata createHibernateSchema() {
    Map<String, List<IndexInfo>> indexes = new HashMap<>();

    indexes.put(
        "users",
        List.of(
            new IndexInfo("users", "PRIMARY", "id", 1, false, 10000),
            new IndexInfo("users", "idx_email", "email", 1, false, 10000)));
    indexes.put(
        "teams",
        List.of(
            new IndexInfo("teams", "PRIMARY", "id", 1, false, 100),
            new IndexInfo("teams", "idx_name", "name", 1, true, 100)));
    indexes.put(
        "members",
        List.of(
            new IndexInfo("members", "PRIMARY", "id", 1, false, 5000),
            new IndexInfo("members", "idx_team_id", "team_id", 1, true, 100)));
    indexes.put(
        "posts",
        List.of(
            new IndexInfo("posts", "PRIMARY", "id", 1, false, 50000),
            new IndexInfo("posts", "idx_author_id", "author_id", 1, true, 10000),
            new IndexInfo("posts", "idx_created_at", "created_at", 1, true, 40000)));
    indexes.put(
        "comments",
        List.of(
            new IndexInfo("comments", "PRIMARY", "id", 1, false, 200000),
            new IndexInfo("comments", "idx_post_id", "post_id", 1, true, 50000),
            new IndexInfo("comments", "idx_author_id", "author_id", 1, true, 10000)));
    indexes.put(
        "tags",
        List.of(
            new IndexInfo("tags", "PRIMARY", "id", 1, false, 500),
            new IndexInfo("tags", "idx_name", "name", 1, false, 500)));
    indexes.put(
        "post_tags",
        List.of(
            new IndexInfo("post_tags", "idx_post_id", "post_id", 1, true, 50000),
            new IndexInfo("post_tags", "idx_tag_id", "tag_id", 1, true, 500)));
    indexes.put(
        "audit_log",
        List.of(
            new IndexInfo("audit_log", "PRIMARY", "id", 1, false, 1000000),
            new IndexInfo("audit_log", "idx_created_at", "created_at", 1, true, 800000),
            new IndexInfo("audit_log", "idx_user_id", "user_id", 1, true, 10000)));

    return new IndexMetadata(indexes);
  }

  /**
   * Reporting schema (extends e-commerce with analytics tables): - sales_summary(id PK, product_id
   * idx, date idx, region, total_sales, quantity_sold) - user_activity(id PK, user_id idx,
   * action_type, page, session_id, created_at idx) - daily_revenue(date PK, channel, revenue,
   * order_count)
   */
  private static IndexMetadata createReportingSchema() {
    Map<String, List<IndexInfo>> indexes =
        new HashMap<>(
            createEcommerceSchema().getIndexesForTable("orders") != null ? Map.of() : Map.of());

    // Start with e-commerce schema and add reporting tables
    IndexMetadata ecommerce = createEcommerceSchema();

    Map<String, List<IndexInfo>> combined = new HashMap<>();
    // Re-add e-commerce tables
    for (String table :
        List.of(
            "users",
            "products",
            "categories",
            "orders",
            "order_items",
            "cart_items",
            "payments",
            "reviews",
            "inventory_log")) {
      combined.put(table, ecommerce.getIndexesForTable(table));
    }

    combined.put(
        "sales_summary",
        List.of(
            new IndexInfo("sales_summary", "PRIMARY", "id", 1, false, 500000),
            new IndexInfo("sales_summary", "idx_product_id", "product_id", 1, true, 10000),
            new IndexInfo("sales_summary", "idx_date", "date", 1, true, 365)));
    combined.put(
        "user_activity",
        List.of(
            new IndexInfo("user_activity", "PRIMARY", "id", 1, false, 5000000),
            new IndexInfo("user_activity", "idx_user_id", "user_id", 1, true, 50000),
            new IndexInfo("user_activity", "idx_created_at", "created_at", 1, true, 100000)));
    combined.put(
        "daily_revenue", List.of(new IndexInfo("daily_revenue", "PRIMARY", "date", 1, false, 365)));

    return new IndexMetadata(combined);
  }

  // ---------------------------------------------------------------
  // Precision tracking helper
  // ---------------------------------------------------------------

  /**
   * Categorizes each issue from a report as true positive or false positive based on expected
   * detection types and prints a summary.
   *
   * @param corpusName human-readable name for the corpus
   * @param report the analyzer report
   * @param expectedIssueTypes issue types that are expected (true positives)
   * @param expectedQuerySubstrings SQL substrings where detections are expected
   * @return a PrecisionResult with counts
   */
  private static PrecisionResult evaluatePrecision(
      String corpusName,
      QueryAuditReport report,
      Set<IssueType> expectedIssueTypes,
      Set<String> expectedQuerySubstrings) {

    List<Issue> allIssues = new ArrayList<>();
    allIssues.addAll(report.getConfirmedIssues());
    allIssues.addAll(report.getInfoIssues());

    int truePositives = 0;
    int falsePositives = 0;
    List<String> fpDetails = new ArrayList<>();

    for (Issue issue : allIssues) {
      boolean isExpected = expectedIssueTypes.contains(issue.type());
      boolean matchesQuery =
          expectedQuerySubstrings.stream()
              .anyMatch(
                  sub ->
                      issue.query() != null
                          && issue.query().toLowerCase().contains(sub.toLowerCase()));

      if (isExpected || matchesQuery) {
        truePositives++;
      } else {
        falsePositives++;
        fpDetails.add(
            String.format(
                "  FP: [%s] %s on %s.%s",
                issue.type().getCode(), issue.severity(), issue.table(), issue.column()));
      }
    }

    int total = truePositives + falsePositives;
    double precision = total == 0 ? 1.0 : (double) truePositives / total;

    System.out.println();
    System.out.println("=== " + corpusName + " Precision Report ===");
    System.out.println("Total queries analyzed: " + report.getTotalQueryCount());
    System.out.println("Total issues found: " + allIssues.size());
    System.out.println("  Confirmed (ERROR/WARNING): " + report.getConfirmedIssues().size());
    System.out.println("  Info: " + report.getInfoIssues().size());
    System.out.println("True positives: " + truePositives);
    System.out.println("False positives: " + falsePositives);
    System.out.printf("Precision: %.1f%%%n", precision * 100);
    if (!fpDetails.isEmpty()) {
      System.out.println("False positive details:");
      fpDetails.forEach(System.out::println);
    }
    System.out.println("=".repeat(50));

    return new PrecisionResult(truePositives, falsePositives, precision, allIssues.size());
  }

  record PrecisionResult(
      int truePositives, int falsePositives, double precision, int totalIssues) {}

  // ===============================================================
  // CORPUS 1: Spring PetClinic patterns (~15 queries)
  // ===============================================================

  @Nested
  class PetClinicCorpus {

    private final IndexMetadata schema = createPetClinicSchema();

    /**
     * All PetClinic queries are well-written with explicit columns, proper WHERE clauses, and
     * indexed lookups. They should produce minimal detections.
     */
    @Test
    void analyzeAllQueries() {
      List<QueryRecord> queries =
          List.of(
              // Q1: Owner search by last name (indexed, LIKE with trailing wildcard)
              record(
                  "SELECT id, first_name, last_name, address, city, telephone FROM owners WHERE last_name LIKE ?"),
              // Q2: List all types (small reference table)
              record("SELECT id, name FROM types ORDER BY name"),
              // Q3: Find pets by owner (indexed FK)
              record(
                  "SELECT pets.id, pets.name, pets.birth_date, pets.type_id, pets.owner_id FROM pets WHERE pets.owner_id = ?"),
              // Q4: Find visits by pet (indexed FK)
              record(
                  "SELECT visits.id, visits.visit_date, visits.description, visits.pet_id FROM visits WHERE visits.pet_id = ?"),
              // Q5: Insert new owner
              record(
                  "INSERT INTO owners (first_name, last_name, address, city, telephone) VALUES (?, ?, ?, ?, ?)"),
              // Q6: Update owner
              record(
                  "UPDATE owners SET first_name=?, last_name=?, address=?, city=?, telephone=? WHERE id=?"),
              // Q7: Find owner by ID (PK lookup)
              record(
                  "SELECT id, first_name, last_name, address, city, telephone FROM owners WHERE id = ?"),
              // Q8: Insert new pet
              record("INSERT INTO pets (name, birth_date, type_id, owner_id) VALUES (?, ?, ?, ?)"),
              // Q9: Update pet
              record("UPDATE pets SET name=?, birth_date=?, type_id=?, owner_id=? WHERE id=?"),
              // Q10: Insert new visit
              record("INSERT INTO visits (visit_date, description, pet_id) VALUES (?, ?, ?)"),
              // Q11: Find vet by last name
              record("SELECT id, first_name, last_name FROM vets WHERE last_name = ?"),
              // Q12: Find vet specialties (JOIN)
              record(
                  "SELECT v.id, v.first_name, v.last_name, s.name FROM vets v JOIN vet_specialties vs ON v.id = vs.vet_id JOIN specialties s ON vs.specialty_id = s.id"),
              // Q13: Find pet by ID
              record("SELECT id, name, birth_date, type_id, owner_id FROM pets WHERE id = ?"),
              // Q14: Count owners
              record("SELECT COUNT(*) FROM owners"),
              // Q15: Find pet type by ID
              record("SELECT id, name FROM types WHERE id = ?"));

      QueryAuditReport report = analyzer.analyze("PetClinicCorpus", queries, schema);

      // --- True positive expectations ---
      // These are INFO-level detections that are legitimate observations:
      // - UNBOUNDED_RESULT_SET on Q2 (SELECT without LIMIT on types) and Q12 (vet specialties join)
      //   are acceptable INFO warnings.

      // --- False positive checks ---
      // PetClinic queries are well-indexed. There should be no ERROR-level issues.
      assertThat(report.getErrors())
          .as("PetClinic queries should not trigger ERROR-level issues")
          .isEmpty();

      // No SELECT * usage
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.SELECT_ALL)
                  .toList())
          .as("PetClinic does not use SELECT *")
          .isEmpty();

      // No missing WHERE index (all WHERE columns are indexed)
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.MISSING_WHERE_INDEX)
                  .toList())
          .as("All PetClinic WHERE columns have indexes")
          .isEmpty();

      // No cartesian joins
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.CARTESIAN_JOIN)
                  .toList())
          .isEmpty();

      // Precision evaluation
      PrecisionResult result =
          evaluatePrecision(
              "Spring PetClinic",
              report,
              // Expected: UNBOUNDED_RESULT_SET on reference table queries is acceptable
              Set.of(IssueType.UNBOUNDED_RESULT_SET, IssueType.COVERING_INDEX_OPPORTUNITY),
              Set.of());

      System.out.println("PetClinic total queries: " + queries.size());
    }

    @Test
    void noFalsePositiveOnIndexedLookups() {
      // Individual PK lookups should produce zero confirmed issues
      List<QueryRecord> queries =
          List.of(
              record("SELECT id, first_name, last_name FROM owners WHERE id = ?"),
              record("SELECT id, name FROM types WHERE id = ?"),
              record("SELECT id, name, birth_date FROM pets WHERE id = ?"));

      QueryAuditReport report = analyzer.analyze("PetClinic_PKLookups", queries, schema);

      assertThat(report.getConfirmedIssues())
          .as("PK lookups should not trigger any confirmed issues")
          .isEmpty();
    }
  }

  // ===============================================================
  // CORPUS 2: E-commerce application patterns (~20 queries)
  // ===============================================================

  @Nested
  class EcommerceCorpus {

    private final IndexMetadata schema = createEcommerceSchema();

    @Test
    void analyzeGoodQueries() {
      // These are well-written queries that should NOT trigger confirmed issues
      List<QueryRecord> goodQueries =
          List.of(
              // Product listing with pagination
              record(
                  "SELECT id, name, price, sku FROM products WHERE category_id = ? ORDER BY price LIMIT 20 OFFSET 0"),
              // Order by user (indexed FK)
              record(
                  "SELECT id, total_amount, created_at FROM orders WHERE user_id = ? ORDER BY created_at DESC LIMIT 10"),
              // Cart items for user
              record(
                  "SELECT ci.id, ci.quantity, p.name, p.price FROM cart_items ci JOIN products p ON ci.product_id = p.id WHERE ci.user_id = ?"),
              // User authentication by email (unique index)
              record("SELECT id, email, password_hash FROM users WHERE email = ?"),
              // Single order lookup
              record("SELECT id, user_id, total_amount, created_at FROM orders WHERE id = ?"),
              // Order items for order
              record(
                  "SELECT oi.id, oi.quantity, oi.unit_price, p.name FROM order_items oi JOIN products p ON oi.product_id = p.id WHERE oi.order_id = ?"),
              // Payment for order (unique index)
              record("SELECT id, payment_method, amount, status FROM payments WHERE order_id = ?"),
              // Product reviews (indexed)
              record(
                  "SELECT id, rating, comment, created_at FROM reviews WHERE product_id = ? ORDER BY created_at DESC LIMIT 10"),
              // Insert order
              record(
                  "INSERT INTO orders (user_id, status, total_amount, created_at, shipping_address) VALUES (?, ?, ?, ?, ?)"),
              // Insert order item
              record(
                  "INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (?, ?, ?, ?)"),
              // Update order status
              record("UPDATE orders SET status = ? WHERE id = ?"),
              // Inventory update
              record(
                  "UPDATE products SET stock_quantity = stock_quantity - ? WHERE id = ? AND stock_quantity >= ?"));

      QueryAuditReport report = analyzer.analyze("Ecommerce_Good", goodQueries, schema);

      // No ERROR issues on well-indexed queries
      assertThat(report.getErrors())
          .as("Well-written e-commerce queries should not trigger errors")
          .isEmpty();

      // No SELECT * usage
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.SELECT_ALL)
                  .toList())
          .isEmpty();

      // No cartesian joins
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.CARTESIAN_JOIN)
                  .toList())
          .isEmpty();
    }

    @Test
    void analyzeProblematicQueries() {
      // These queries have known issues that SHOULD be detected
      List<QueryRecord> badQueries =
          List.of(
              // BAD: SELECT * from large table
              record("SELECT * FROM products WHERE category_id = ?"),
              // BAD: Search with function on column (non-sargable)
              record("SELECT id, name FROM users WHERE LOWER(email) = ?"),
              // BAD: Large OFFSET pagination
              record(
                  "SELECT id, name, price FROM products ORDER BY created_at LIMIT 20 OFFSET 50000"),
              // BAD: UPDATE without WHERE
              record("UPDATE products SET price = price * 1.1"),
              // BAD: NULL comparison with =
              record("SELECT id, name FROM users WHERE email = NULL"),
              // BAD: Cartesian join (missing ON)
              record("SELECT p.name, c.name FROM products p, categories c"),
              // BAD: UNION without ALL (unnecessary dedup)
              record(
                  "SELECT id, name FROM products WHERE price > 100 UNION SELECT id, name FROM products WHERE category_id = 5"),
              // BAD: HAVING on non-aggregate column
              record(
                  "SELECT category_id, COUNT(*) FROM products GROUP BY category_id HAVING category_id > 5"));

      QueryAuditReport report = analyzer.analyze("Ecommerce_Bad", badQueries, schema);

      // All problematic queries should trigger at least one confirmed issue
      assertThat(report.getConfirmedIssues())
          .as("Problematic queries should be detected")
          .isNotEmpty();

      // Verify specific detections:
      List<IssueType> detectedTypes =
          report.getConfirmedIssues().stream().map(Issue::type).toList();

      // All issue types (confirmed + info)
      List<IssueType> allTypes = new ArrayList<>(detectedTypes);
      report.getInfoIssues().stream().map(Issue::type).forEach(allTypes::add);

      // SELECT_ALL is INFO severity, so check across all issues
      assertThat(allTypes).as("SELECT * should be detected").contains(IssueType.SELECT_ALL);

      assertThat(detectedTypes)
          .as("Function in WHERE should be detected")
          .contains(IssueType.WHERE_FUNCTION);

      assertThat(detectedTypes)
          .as("UPDATE without WHERE should be detected")
          .contains(IssueType.UPDATE_WITHOUT_WHERE);

      // NULL comparison detection
      assertThat(allTypes).contains(IssueType.NULL_COMPARISON);

      // Cartesian join
      assertThat(detectedTypes).contains(IssueType.CARTESIAN_JOIN);

      // Precision evaluation
      PrecisionResult result =
          evaluatePrecision(
              "E-commerce (Bad Queries)",
              report,
              Set.of(
                  IssueType.SELECT_ALL,
                  IssueType.WHERE_FUNCTION,
                  IssueType.OFFSET_PAGINATION,
                  IssueType.UPDATE_WITHOUT_WHERE,
                  IssueType.NULL_COMPARISON,
                  IssueType.CARTESIAN_JOIN,
                  IssueType.UNION_WITHOUT_ALL,
                  IssueType.HAVING_MISUSE,
                  IssueType.UNBOUNDED_RESULT_SET,
                  IssueType.MISSING_WHERE_INDEX,
                  IssueType.MISSING_ORDER_BY_INDEX,
                  IssueType.MISSING_GROUP_BY_INDEX,
                  IssueType.COVERING_INDEX_OPPORTUNITY),
              Set.of(
                  "products set price",
                  "lower(email)",
                  "offset 50000",
                  "email = null",
                  "products p, categories c",
                  "union select",
                  "having category_id"));

      assertThat(result.truePositives())
          .as("Should detect multiple true positive issues")
          .isGreaterThanOrEqualTo(5);
    }

    @Test
    void analyzeSearchWithMultipleFilters() {
      List<QueryRecord> queries =
          List.of(
              record(
                  "SELECT id, name, price FROM products WHERE category_id = ? AND price BETWEEN ? AND ? ORDER BY price LIMIT 20"));

      QueryAuditReport report = analyzer.analyze("Ecommerce_Search", queries, schema);

      // category_id is indexed; price is not but category_id narrows the scan.
      // Should NOT be an ERROR.
      assertThat(report.getErrors())
          .as("Multi-filter with one indexed column should not be ERROR")
          .isEmpty();
    }
  }

  // ===============================================================
  // CORPUS 3: Hibernate/JPA generated patterns (~20 queries)
  // ===============================================================

  @Nested
  class HibernateJpaCorpus {

    private final IndexMetadata schema = createHibernateSchema();

    @Test
    void analyzeHibernateAliasQueries() {
      // Hibernate 6 alias style: table1_0 aliases
      List<QueryRecord> queries =
          List.of(
              // Hibernate SELECT with aliases
              record("select u1_0.id,u1_0.name,u1_0.email from users u1_0 where u1_0.id=?"),
              // Lazy loading pattern
              record(
                  "select m1_0.id,m1_0.name,m1_0.team_id from members m1_0 where m1_0.team_id=?"),
              // Another lazy load
              record(
                  "select c1_0.id,c1_0.content,c1_0.created_at from comments c1_0 where c1_0.post_id=?"),
              // Hibernate JOIN fetch
              record(
                  "select t1_0.id,t1_0.name,m1_0.id,m1_0.name from teams t1_0 left join members m1_0 on t1_0.id=m1_0.team_id where t1_0.id=?"),
              // Spring Data findByEmail
              record(
                  "select u1_0.id,u1_0.name,u1_0.email,u1_0.version,u1_0.created_at from users u1_0 where u1_0.email=?"),
              // Spring Data findByNameContaining
              record(
                  "select t1_0.id,t1_0.name,t1_0.description from teams t1_0 where t1_0.name like ?"),
              // Hibernate count query for pagination
              record("select count(p1_0.id) from posts p1_0 where p1_0.author_id=?"),
              // Paginated query
              record(
                  "select p1_0.id,p1_0.title,p1_0.created_at from posts p1_0 where p1_0.author_id=? order by p1_0.created_at desc limit ?"));

      QueryAuditReport report = analyzer.analyze("Hibernate_Aliases", queries, schema);

      // Hibernate alias queries with indexed columns should not trigger ERRORs
      assertThat(report.getErrors())
          .as("Hibernate alias-style queries on indexed columns should not produce errors")
          .isEmpty();

      // No SELECT * (Hibernate always specifies columns)
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.SELECT_ALL)
                  .toList())
          .isEmpty();

      PrecisionResult result =
          evaluatePrecision(
              "Hibernate/JPA (Alias Queries)",
              report,
              Set.of(IssueType.UNBOUNDED_RESULT_SET, IssueType.COVERING_INDEX_OPPORTUNITY),
              Set.of());
    }

    @Test
    void analyzeJpqlGeneratedSql() {
      // @Query JPQL translated to SQL
      List<QueryRecord> queries =
          List.of(
              // @Query("SELECT p FROM Post p WHERE p.category = :cat AND p.published = true")
              record(
                  "select p1_0.id,p1_0.title,p1_0.body,p1_0.author_id,p1_0.category,p1_0.published,p1_0.created_at,p1_0.version from posts p1_0 where p1_0.category=? and p1_0.published=?"),
              // @Query with JOIN
              record(
                  "select p1_0.id,p1_0.title from posts p1_0 join comments c1_0 on p1_0.id=c1_0.post_id where c1_0.author_id=? group by p1_0.id"),
              // Derived query: findByAuthorIdAndCreatedAtAfter
              record(
                  "select p1_0.id,p1_0.title,p1_0.created_at from posts p1_0 where p1_0.author_id=? and p1_0.created_at>?"),
              // existsBy check
              record("select count(u1_0.id) from users u1_0 where u1_0.email=?"));

      QueryAuditReport report = analyzer.analyze("JPQL_Generated", queries, schema);

      // No ERROR-level issues (all columns referenced have indexes or the schema covers them)
      assertThat(report.getErrors())
          .as("JPQL-generated queries should not trigger errors with proper schema")
          .isEmpty();
    }

    @Test
    void analyzeBatchInsertAndOptimisticLocking() {
      List<QueryRecord> queries =
          List.of(
              // Hibernate batch insert with sequence
              record("select nextval('posts_id_seq')"),
              record(
                  "insert into posts (id,title,body,author_id,category,published,created_at,version) values (?,?,?,?,?,?,?,?)"),
              // Optimistic locking: UPDATE with version check
              record("update posts set title=?,body=?,version=? where id=? and version=?"),
              // Another optimistic lock update
              record("update users set name=?,email=?,version=? where id=? and version=?"),
              // Batch insert for tags
              record("insert into post_tags (post_id,tag_id) values (?,?)"),
              record("insert into post_tags (post_id,tag_id) values (?,?)"),
              // Delete with WHERE
              record("delete from comments where id=?"),
              // Hibernate generated SELECT for @Version
              record("select p1_0.id,p1_0.version from posts p1_0 where p1_0.id=?"));

      QueryAuditReport report = analyzer.analyze("Hibernate_Batch", queries, schema);

      // Inserts and optimistic lock updates should not trigger critical errors.
      // The two consecutive INSERT INTO post_tags might trigger REPEATED_SINGLE_INSERT which is
      // valid.
      assertThat(report.getErrors())
          .as("Batch inserts and optimistic lock updates should not cause errors")
          .isEmpty();

      PrecisionResult result =
          evaluatePrecision(
              "Hibernate/JPA (Batch & Locking)",
              report,
              // REPEATED_SINGLE_INSERT on post_tags is expected and valid
              Set.of(
                  IssueType.REPEATED_SINGLE_INSERT,
                  IssueType.UNBOUNDED_RESULT_SET,
                  IssueType.COVERING_INDEX_OPPORTUNITY),
              Set.of("post_tags"));
    }

    @Test
    void analyzeNPlusOnePattern() {
      // Simulate N+1: fetch team, then lazy-load members for each team
      List<QueryRecord> queries = new ArrayList<>();
      queries.add(record("select t1_0.id,t1_0.name from teams t1_0"));
      // Simulate 5 lazy loads (above N+1 threshold of 3)
      for (int i = 1; i <= 5; i++) {
        queries.add(
            record("select m1_0.id,m1_0.name,m1_0.team_id from members m1_0 where m1_0.team_id=?"));
      }

      QueryAuditReport report = analyzer.analyze("Hibernate_NPlusOne", queries, schema);

      // N+1 should be detected (at least as INFO for SQL-level)
      List<Issue> allIssues = new ArrayList<>();
      allIssues.addAll(report.getConfirmedIssues());
      allIssues.addAll(report.getInfoIssues());

      assertThat(allIssues.stream().filter(i -> i.type() == IssueType.N_PLUS_ONE_SUSPECT).toList())
          .as("N+1 pattern should be detected")
          .isNotEmpty();
    }
  }

  // ===============================================================
  // CORPUS 4: Reporting/Analytics patterns (~10 queries)
  // ===============================================================

  @Nested
  class ReportingCorpus {

    private final IndexMetadata schema = createReportingSchema();

    @Test
    void analyzeReportingQueries() {
      List<QueryRecord> queries =
          List.of(
              // Legitimate GROUP BY with HAVING on aggregate
              record(
                  "SELECT category_id, COUNT(*) as cnt, AVG(price) as avg_price FROM products GROUP BY category_id HAVING COUNT(*) > 10"),
              // UNION ALL for combined report (legitimate)
              record(
                  "SELECT 'online' as channel, SUM(total_amount) as revenue FROM orders WHERE created_at >= ? UNION ALL SELECT 'in_store' as channel, SUM(revenue) as revenue FROM daily_revenue WHERE date >= ?"),
              // Subquery for aggregation
              record(
                  "SELECT p.id, p.name, (SELECT AVG(r.rating) FROM reviews r WHERE r.product_id = p.id) as avg_rating FROM products p WHERE p.category_id = ? LIMIT 20"),
              // Window function (analytics)
              record(
                  "SELECT user_id, total_amount, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) as rn FROM orders WHERE created_at >= ?"),
              // Complex JOIN for dashboard
              record(
                  "SELECT o.id, o.total_amount, u.email, COUNT(oi.id) as item_count FROM orders o JOIN users u ON o.user_id = u.id JOIN order_items oi ON o.id = oi.order_id WHERE o.created_at >= ? GROUP BY o.id, o.total_amount, u.email ORDER BY o.total_amount DESC LIMIT 50"),
              // Date-range report with aggregation
              record(
                  "SELECT DATE(created_at) as order_date, COUNT(*) as order_count, SUM(total_amount) as daily_total FROM orders WHERE created_at BETWEEN ? AND ? GROUP BY DATE(created_at) ORDER BY order_date"),
              // Top products report
              record(
                  "SELECT p.id, p.name, SUM(oi.quantity) as total_sold FROM products p JOIN order_items oi ON p.id = oi.product_id GROUP BY p.id, p.name ORDER BY total_sold DESC LIMIT 10"),
              // User activity summary
              record(
                  "SELECT user_id, action_type, COUNT(*) as action_count FROM user_activity WHERE created_at >= ? AND created_at < ? GROUP BY user_id, action_type"),
              // Revenue by month with running total
              record(
                  "SELECT date, revenue, SUM(revenue) OVER (ORDER BY date) as running_total FROM daily_revenue WHERE date >= ? AND date <= ?"),
              // Sales comparison subquery
              record(
                  "SELECT ss.product_id, ss.total_sales FROM sales_summary ss WHERE ss.date >= ? AND ss.total_sales > (SELECT AVG(total_sales) FROM sales_summary WHERE date >= ?)"));

      QueryAuditReport report = analyzer.analyze("Reporting", queries, schema);

      // Reporting queries often use GROUP BY, HAVING, subqueries -- these are legitimate
      // patterns. Correlated subquery detection is expected on the avg_rating subquery.
      // WHERE FUNCTION for DATE(created_at) is a true positive.

      // Cartesian joins should NOT be detected (all JOINs have proper ON clauses)
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.CARTESIAN_JOIN)
                  .toList())
          .as("Reporting queries with proper JOINs should not trigger cartesian join")
          .isEmpty();

      PrecisionResult result =
          evaluatePrecision(
              "Reporting/Analytics",
              report,
              Set.of(
                  IssueType.CORRELATED_SUBQUERY, IssueType.WHERE_FUNCTION,
                  IssueType.UNBOUNDED_RESULT_SET, IssueType.COVERING_INDEX_OPPORTUNITY,
                  IssueType.MISSING_GROUP_BY_INDEX, IssueType.MISSING_ORDER_BY_INDEX,
                  IssueType.MISSING_WHERE_INDEX, IssueType.NON_SARGABLE_EXPRESSION),
              Set.of("date(created_at)", "avg(r.rating)"));

      System.out.println("Reporting total queries: " + queries.size());
    }

    @Test
    void legitimateHavingOnAggregate() {
      List<QueryRecord> queries =
          List.of(
              record(
                  "SELECT category_id, COUNT(*) as cnt FROM products GROUP BY category_id HAVING COUNT(*) > 5"));

      QueryAuditReport report = analyzer.analyze("Reporting_Having", queries, schema);

      // HAVING on COUNT(*) is legitimate -- should NOT be flagged as HAVING_MISUSE
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.HAVING_MISUSE)
                  .toList())
          .as("HAVING on aggregate function should not be flagged as misuse")
          .isEmpty();
    }
  }

  // ===============================================================
  // CORPUS 5: Admin/Migration patterns (~10 queries)
  // ===============================================================

  @Nested
  class AdminMigrationCorpus {

    private final IndexMetadata schema = createEcommerceSchema();

    @Test
    void analyzeAdminQueries() {
      List<QueryRecord> queries =
          List.of(
              // Bulk UPDATE with WHERE (legitimate admin operation)
              record("UPDATE products SET price = price * 1.05 WHERE category_id = ?"),
              // DELETE old records with date filter
              record("DELETE FROM cart_items WHERE created_at < ?"),
              // INSERT ... SELECT for data migration
              record(
                  "INSERT INTO inventory_log (product_id, change_amount, reason, created_at) SELECT id, stock_quantity, 'snapshot', NOW() FROM products WHERE category_id = ?"),
              // Bulk status update
              record(
                  "UPDATE orders SET status = 'archived' WHERE created_at < ? AND status = 'completed'"),
              // Cleanup expired sessions
              record("DELETE FROM cart_items WHERE user_id = ? AND created_at < ?"),
              // Migration: copy data between tables
              record(
                  "INSERT INTO reviews (product_id, user_id, rating, comment, created_at) SELECT product_id, user_id, rating, comment, created_at FROM reviews WHERE created_at >= ?"),
              // Admin: count by status
              record("SELECT COUNT(*) FROM orders WHERE status = ?"),
              // Admin: list recent orders
              record(
                  "SELECT id, user_id, total_amount, status, created_at FROM orders WHERE created_at >= ? ORDER BY created_at DESC LIMIT 100"),
              // Admin: deactivate user
              record("UPDATE users SET status = 'inactive' WHERE id = ?"),
              // DDL: ALTER TABLE (should not crash analyzers)
              record("ALTER TABLE products ADD COLUMN weight DECIMAL(10,2)"));

      QueryAuditReport report = analyzer.analyze("Admin_Migration", queries, schema);

      // The analyzer should not throw exceptions on any of these queries,
      // including DDL (ALTER TABLE).
      assertThat(report).isNotNull();

      // DELETE without index on created_at column is a valid detection
      // DML_WITHOUT_INDEX on cart_items.created_at is expected (no index)

      // UPDATE without WHERE should NOT be triggered (all UPDATEs have WHERE)
      assertThat(
              report.getConfirmedIssues().stream()
                  .filter(i -> i.type() == IssueType.UPDATE_WITHOUT_WHERE)
                  .toList())
          .as("All admin UPDATEs have WHERE clauses")
          .isEmpty();

      PrecisionResult result =
          evaluatePrecision(
              "Admin/Migration",
              report,
              Set.of(
                  IssueType.DML_WITHOUT_INDEX, IssueType.UNBOUNDED_RESULT_SET,
                  IssueType.INSERT_SELECT_ALL, IssueType.COVERING_INDEX_OPPORTUNITY,
                  IssueType.MISSING_WHERE_INDEX, IssueType.MISSING_ORDER_BY_INDEX),
              Set.of("cart_items where created_at", "delete from cart_items"));

      System.out.println("Admin/Migration total queries: " + queries.size());
    }

    @Test
    void alterTableDoesNotCrash() {
      List<QueryRecord> queries =
          List.of(
              record("ALTER TABLE products ADD COLUMN weight DECIMAL(10,2)"),
              record("ALTER TABLE users ADD INDEX idx_status (status)"),
              record("CREATE INDEX idx_price ON products (price)"));

      QueryAuditReport report = analyzer.analyze("DDL_Statements", queries, schema);

      // Should complete without exceptions
      assertThat(report).isNotNull();
      assertThat(report.getTotalQueryCount()).isEqualTo(3);
    }
  }

  // ===============================================================
  // AGGREGATE: Full corpus benchmark
  // ===============================================================

  @Test
  void fullCorpusBenchmark() {
    // Collect ALL queries from every corpus and run a combined analysis
    IndexMetadata combinedSchema =
        createEcommerceSchema()
            .merge(createHibernateSchema())
            .merge(createReportingSchema())
            .merge(createPetClinicSchema());

    List<QueryRecord> allQueries = new ArrayList<>();

    // PetClinic (~15)
    allQueries.addAll(
        List.of(
            record(
                "SELECT id, first_name, last_name, address, city, telephone FROM owners WHERE last_name LIKE ?"),
            record("SELECT id, name FROM types ORDER BY name"),
            record(
                "SELECT pets.id, pets.name, pets.birth_date, pets.type_id, pets.owner_id FROM pets WHERE pets.owner_id = ?"),
            record(
                "SELECT visits.id, visits.visit_date, visits.description, visits.pet_id FROM visits WHERE visits.pet_id = ?"),
            record(
                "INSERT INTO owners (first_name, last_name, address, city, telephone) VALUES (?, ?, ?, ?, ?)"),
            record(
                "UPDATE owners SET first_name=?, last_name=?, address=?, city=?, telephone=? WHERE id=?"),
            record(
                "SELECT id, first_name, last_name, address, city, telephone FROM owners WHERE id = ?"),
            record("INSERT INTO pets (name, birth_date, type_id, owner_id) VALUES (?, ?, ?, ?)"),
            record("UPDATE pets SET name=?, birth_date=?, type_id=?, owner_id=? WHERE id=?"),
            record("INSERT INTO visits (visit_date, description, pet_id) VALUES (?, ?, ?)"),
            record("SELECT id, first_name, last_name FROM vets WHERE last_name = ?"),
            record(
                "SELECT v.id, v.first_name, v.last_name, s.name FROM vets v JOIN vet_specialties vs ON v.id = vs.vet_id JOIN specialties s ON vs.specialty_id = s.id"),
            record("SELECT id, name, birth_date, type_id, owner_id FROM pets WHERE id = ?"),
            record("SELECT COUNT(*) FROM owners"),
            record("SELECT id, name FROM types WHERE id = ?")));

    // E-commerce good (~12)
    allQueries.addAll(
        List.of(
            record(
                "SELECT id, name, price, sku FROM products WHERE category_id = ? ORDER BY price LIMIT 20 OFFSET 0"),
            record(
                "SELECT id, total_amount, created_at FROM orders WHERE user_id = ? ORDER BY created_at DESC LIMIT 10"),
            record(
                "SELECT ci.id, ci.quantity, p.name, p.price FROM cart_items ci JOIN products p ON ci.product_id = p.id WHERE ci.user_id = ?"),
            record("SELECT id, email, password_hash FROM users WHERE email = ?"),
            record("SELECT id, user_id, total_amount, created_at FROM orders WHERE id = ?"),
            record(
                "SELECT oi.id, oi.quantity, oi.unit_price, p.name FROM order_items oi JOIN products p ON oi.product_id = p.id WHERE oi.order_id = ?"),
            record("SELECT id, payment_method, amount, status FROM payments WHERE order_id = ?"),
            record(
                "SELECT id, rating, comment, created_at FROM reviews WHERE product_id = ? ORDER BY created_at DESC LIMIT 10"),
            record(
                "INSERT INTO orders (user_id, status, total_amount, created_at, shipping_address) VALUES (?, ?, ?, ?, ?)"),
            record(
                "INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (?, ?, ?, ?)"),
            record("UPDATE orders SET status = ? WHERE id = ?"),
            record(
                "UPDATE products SET stock_quantity = stock_quantity - ? WHERE id = ? AND stock_quantity >= ?")));

    // E-commerce bad (~8)
    allQueries.addAll(
        List.of(
            record("SELECT * FROM products WHERE category_id = ?"),
            record("SELECT id, name FROM users WHERE LOWER(email) = ?"),
            record(
                "SELECT id, name, price FROM products ORDER BY created_at LIMIT 20 OFFSET 50000"),
            record("UPDATE products SET price = price * 1.1"),
            record("SELECT id, name FROM users WHERE email = NULL"),
            record("SELECT p.name, c.name FROM products p, categories c"),
            record(
                "SELECT id, name FROM products WHERE price > 100 UNION SELECT id, name FROM products WHERE category_id = 5"),
            record(
                "SELECT category_id, COUNT(*) FROM products GROUP BY category_id HAVING category_id > 5")));

    // Hibernate/JPA (~20)
    allQueries.addAll(
        List.of(
            record("select u1_0.id,u1_0.name,u1_0.email from users u1_0 where u1_0.id=?"),
            record("select m1_0.id,m1_0.name,m1_0.team_id from members m1_0 where m1_0.team_id=?"),
            record(
                "select c1_0.id,c1_0.content,c1_0.created_at from comments c1_0 where c1_0.post_id=?"),
            record(
                "select t1_0.id,t1_0.name,m1_0.id,m1_0.name from teams t1_0 left join members m1_0 on t1_0.id=m1_0.team_id where t1_0.id=?"),
            record(
                "select u1_0.id,u1_0.name,u1_0.email,u1_0.version,u1_0.created_at from users u1_0 where u1_0.email=?"),
            record(
                "select t1_0.id,t1_0.name,t1_0.description from teams t1_0 where t1_0.name like ?"),
            record("select count(p1_0.id) from posts p1_0 where p1_0.author_id=?"),
            record(
                "select p1_0.id,p1_0.title,p1_0.created_at from posts p1_0 where p1_0.author_id=? order by p1_0.created_at desc limit ?"),
            record(
                "insert into posts (id,title,body,author_id,category,published,created_at,version) values (?,?,?,?,?,?,?,?)"),
            record("update posts set title=?,body=?,version=? where id=? and version=?"),
            record("update users set name=?,email=?,version=? where id=? and version=?"),
            record("delete from comments where id=?"),
            // Hibernate @Query with JPQL-generated SQL (category + published filter)
            record(
                "select p1_0.id,p1_0.title,p1_0.body,p1_0.author_id,p1_0.category,p1_0.published,p1_0.created_at,p1_0.version from posts p1_0 where p1_0.category=? and p1_0.published=?"),
            // Derived query: findByAuthorIdAndCreatedAtAfter
            record(
                "select p1_0.id,p1_0.title,p1_0.created_at from posts p1_0 where p1_0.author_id=? and p1_0.created_at>?"),
            // Spring Data existsBy
            record("select count(u1_0.id) from users u1_0 where u1_0.email=?"),
            // Hibernate batch insert (post_tags)
            record("insert into post_tags (post_id,tag_id) values (?,?)"),
            // Hibernate SELECT for @Version check
            record("select p1_0.id,p1_0.version from posts p1_0 where p1_0.id=?"),
            // Hibernate: fetch tags for a post
            record(
                "select t1_0.id,t1_0.name from tags t1_0 join post_tags pt1_0 on t1_0.id=pt1_0.tag_id where pt1_0.post_id=?"),
            // MyBatis-style plain JDBC query
            record("SELECT id, name, email FROM users WHERE id IN (?, ?, ?)"),
            // Plain JDBC batch lookup
            record("SELECT id, name, price FROM products WHERE id IN (?, ?, ?, ?, ?)")));

    // Reporting (~10)
    allQueries.addAll(
        List.of(
            record(
                "SELECT category_id, COUNT(*) as cnt, AVG(price) as avg_price FROM products GROUP BY category_id HAVING COUNT(*) > 10"),
            record(
                "SELECT 'online' as channel, SUM(total_amount) as revenue FROM orders WHERE created_at >= ? UNION ALL SELECT 'in_store' as channel, SUM(revenue) as revenue FROM daily_revenue WHERE date >= ?"),
            record(
                "SELECT p.id, p.name, (SELECT AVG(r.rating) FROM reviews r WHERE r.product_id = p.id) as avg_rating FROM products p WHERE p.category_id = ? LIMIT 20"),
            record(
                "SELECT user_id, total_amount, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) as rn FROM orders WHERE created_at >= ?"),
            record(
                "SELECT o.id, o.total_amount, u.email, COUNT(oi.id) as item_count FROM orders o JOIN users u ON o.user_id = u.id JOIN order_items oi ON o.id = oi.order_id WHERE o.created_at >= ? GROUP BY o.id, o.total_amount, u.email ORDER BY o.total_amount DESC LIMIT 50"),
            record(
                "SELECT DATE(created_at) as order_date, COUNT(*) as order_count, SUM(total_amount) as daily_total FROM orders WHERE created_at BETWEEN ? AND ? GROUP BY DATE(created_at) ORDER BY order_date"),
            record(
                "SELECT p.id, p.name, SUM(oi.quantity) as total_sold FROM products p JOIN order_items oi ON p.id = oi.product_id GROUP BY p.id, p.name ORDER BY total_sold DESC LIMIT 10"),
            record(
                "SELECT user_id, action_type, COUNT(*) as action_count FROM user_activity WHERE created_at >= ? AND created_at < ? GROUP BY user_id, action_type"),
            record(
                "SELECT date, revenue, SUM(revenue) OVER (ORDER BY date) as running_total FROM daily_revenue WHERE date >= ? AND date <= ?"),
            record(
                "SELECT ss.product_id, ss.total_sales FROM sales_summary ss WHERE ss.date >= ? AND ss.total_sales > (SELECT AVG(total_sales) FROM sales_summary WHERE date >= ?)")));

    // Admin/Migration (~10)
    allQueries.addAll(
        List.of(
            record("UPDATE products SET price = price * 1.05 WHERE category_id = ?"),
            record("DELETE FROM cart_items WHERE created_at < ?"),
            record(
                "INSERT INTO inventory_log (product_id, change_amount, reason, created_at) SELECT id, stock_quantity, 'snapshot', NOW() FROM products WHERE category_id = ?"),
            record(
                "UPDATE orders SET status = 'archived' WHERE created_at < ? AND status = 'completed'"),
            record("DELETE FROM cart_items WHERE user_id = ? AND created_at < ?"),
            record(
                "INSERT INTO reviews (product_id, user_id, rating, comment, created_at) SELECT product_id, user_id, rating, comment, created_at FROM reviews WHERE created_at >= ?"),
            record("SELECT COUNT(*) FROM orders WHERE status = ?"),
            record(
                "SELECT id, user_id, total_amount, status, created_at FROM orders WHERE created_at >= ? ORDER BY created_at DESC LIMIT 100"),
            record("UPDATE users SET status = 'inactive' WHERE id = ?"),
            record("ALTER TABLE products ADD COLUMN weight DECIMAL(10,2)")));

    // Verify we have at least 75 queries
    assertThat(allQueries.size())
        .as("Full corpus should contain at least 75 queries")
        .isGreaterThanOrEqualTo(75);

    // Run the full analysis
    QueryAuditReport report = analyzer.analyze("FullCorpusBenchmark", allQueries, combinedSchema);

    assertThat(report).isNotNull();
    assertThat(report.getTotalQueryCount())
        .as("All queries should be processed")
        .isGreaterThanOrEqualTo(75);

    // --- Aggregate precision report ---
    List<Issue> allIssues = new ArrayList<>();
    allIssues.addAll(report.getConfirmedIssues());
    allIssues.addAll(report.getInfoIssues());

    // Known true positive issue types for the intentionally-bad queries
    Set<IssueType> knownTruePositiveTypes =
        Set.of(
            IssueType.SELECT_ALL,
            IssueType.WHERE_FUNCTION,
            IssueType.OFFSET_PAGINATION,
            IssueType.UPDATE_WITHOUT_WHERE,
            IssueType.NULL_COMPARISON,
            IssueType.CARTESIAN_JOIN,
            IssueType.UNION_WITHOUT_ALL,
            IssueType.HAVING_MISUSE,
            IssueType.CORRELATED_SUBQUERY,
            IssueType.N_PLUS_ONE,
            IssueType.N_PLUS_ONE_SUSPECT,
            IssueType.UNBOUNDED_RESULT_SET,
            IssueType.DML_WITHOUT_INDEX,
            IssueType.COVERING_INDEX_OPPORTUNITY,
            IssueType.MISSING_WHERE_INDEX,
            IssueType.MISSING_ORDER_BY_INDEX,
            IssueType.MISSING_GROUP_BY_INDEX,
            IssueType.NON_SARGABLE_EXPRESSION,
            IssueType.REPEATED_SINGLE_INSERT);

    PrecisionResult result =
        evaluatePrecision(
            "FULL CORPUS (All Corpora Combined)", report, knownTruePositiveTypes, Set.of());

    System.out.println();
    System.out.println("**** FULL CORPUS SUMMARY ****");
    System.out.println("Total queries: " + allQueries.size());
    System.out.println("Unique query patterns: " + report.getUniquePatternCount());
    System.out.println("Confirmed issues: " + report.getConfirmedIssues().size());
    System.out.println("Info issues: " + report.getInfoIssues().size());
    System.out.println("Errors: " + report.getErrors().size());
    System.out.println("Warnings: " + report.getWarnings().size());

    // Break down by issue type
    Map<IssueType, Long> issueCounts =
        allIssues.stream().collect(Collectors.groupingBy(Issue::type, Collectors.counting()));
    System.out.println("\nIssue type breakdown:");
    issueCounts.entrySet().stream()
        .sorted(Map.Entry.<IssueType, Long>comparingByValue().reversed())
        .forEach(e -> System.out.printf("  %-40s %d%n", e.getKey().getCode(), e.getValue()));

    // Ensure intentionally bad queries are caught
    assertThat(report.getConfirmedIssues())
        .as("Known bad queries should produce confirmed issues")
        .isNotEmpty();

    // Verify known bad patterns are detected
    List<IssueType> confirmedTypes =
        report.getConfirmedIssues().stream().map(Issue::type).distinct().toList();

    List<IssueType> allDetectedTypes = new ArrayList<>(confirmedTypes);
    report.getInfoIssues().stream().map(Issue::type).distinct().forEach(allDetectedTypes::add);

    // SELECT_ALL is now INFO severity
    assertThat(allDetectedTypes)
        .as("SELECT * should be detected in full corpus")
        .contains(IssueType.SELECT_ALL);
    assertThat(confirmedTypes)
        .as("UPDATE without WHERE should be detected in full corpus")
        .contains(IssueType.UPDATE_WITHOUT_WHERE);
    assertThat(confirmedTypes)
        .as("Cartesian join should be detected in full corpus")
        .contains(IssueType.CARTESIAN_JOIN);
  }

  // ===============================================================
  // Cross-cutting: ensure analyzer handles all query types safely
  // ===============================================================

  @Test
  void analyzerDoesNotThrowOnAnyQuery() {
    IndexMetadata schema = createEcommerceSchema();

    // Edge cases that should not cause exceptions
    List<QueryRecord> edgeCases =
        List.of(
            record(""),
            record("   "),
            record("SELECT 1"),
            record("SELECT NOW()"),
            record("SET @var = 1"),
            record("SHOW TABLES"),
            record("DESCRIBE products"),
            record("EXPLAIN SELECT * FROM products WHERE id = 1"),
            record("COMMIT"),
            record("ROLLBACK"),
            record("BEGIN"),
            record("SAVEPOINT sp1"));

    // Should not throw
    QueryAuditReport report = analyzer.analyze("EdgeCases", edgeCases, schema);
    assertThat(report).isNotNull();
  }
}
